import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import {
  createCustomer,
  createPayment,
  createSubscription,
  getSubscriptionPayments,
  getPixQrCode,
} from './asaas'
import type { SubscriptionCycle } from './asaas'

const app = express()
const PORT = process.env.PORT || 3001

app.use(cors({ origin: true }))
app.use(express.json())

/* ── Checkout endpoint (single payment — kept for backward compat) ── */
app.post('/api/checkout', async (req, res) => {
  try {
    const { name, cpfCnpj, email, billingType, value, description, creditCard, creditCardHolderInfo } = req.body

    if (!name || !cpfCnpj || !email || !billingType || !value) {
      res.status(400).json({ error: 'Campos obrigatorios: name, cpfCnpj, email, billingType, value' })
      return
    }

    const customer = await createCustomer({ name, cpfCnpj, email })

    const today = new Date()
    const dueDate = new Date(today.getTime() + 3 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split('T')[0]

    const paymentData: Parameters<typeof createPayment>[0] = {
      customer: customer.id,
      billingType,
      value,
      dueDate,
      description: description || 'Chat Ajax - Assinatura de plano',
    }

    if (billingType === 'CREDIT_CARD' && creditCard) {
      paymentData.creditCard = creditCard
      paymentData.creditCardHolderInfo = creditCardHolderInfo
    }

    const payment = await createPayment(paymentData)

    let pix = null
    if (billingType === 'PIX') {
      pix = await getPixQrCode(payment.id)
    }

    res.json({
      success: true,
      payment: {
        id: payment.id,
        status: payment.status,
        billingType: payment.billingType,
        value: payment.value,
        invoiceUrl: payment.invoiceUrl,
        bankSlipUrl: payment.bankSlipUrl,
      },
      pix,
    })
  } catch (err) {
    console.error('Checkout error:', err)
    const message = err instanceof Error ? err.message : 'Erro interno'
    res.status(500).json({ error: message })
  }
})

/* ── Subscription endpoint (recurring payments) ── */
app.post('/api/subscribe', async (req, res) => {
  try {
    const {
      name, cpfCnpj, email,
      billingType, value, cycle,
      description,
      creditCard, creditCardHolderInfo,
    } = req.body

    if (!name || !cpfCnpj || !email || !billingType || !value || !cycle) {
      res.status(400).json({
        error: 'Campos obrigatorios: name, cpfCnpj, email, billingType, value, cycle',
      })
      return
    }

    const validCycles: SubscriptionCycle[] = ['MONTHLY', 'QUARTERLY', 'SEMIANNUALLY', 'YEARLY']
    if (!validCycles.includes(cycle)) {
      res.status(400).json({ error: `Ciclo invalido. Use: ${validCycles.join(', ')}` })
      return
    }

    // 1. Create customer
    const customer = await createCustomer({ name, cpfCnpj, email })

    // 2. Set next due date (3 days from now for first charge)
    const today = new Date()
    const nextDueDate = new Date(today.getTime() + 3 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split('T')[0]

    // 3. Create subscription
    const subscriptionData: Parameters<typeof createSubscription>[0] = {
      customer: customer.id,
      billingType,
      value,
      nextDueDate,
      cycle,
      description: description || 'Chat Ajax - Assinatura recorrente',
    }

    if (billingType === 'CREDIT_CARD' && creditCard) {
      subscriptionData.creditCard = creditCard
      subscriptionData.creditCardHolderInfo = creditCardHolderInfo
    }

    const subscription = await createSubscription(subscriptionData)

    // 4. Get the first payment generated by the subscription
    let pix = null
    let firstPayment = null

    try {
      const payments = await getSubscriptionPayments(subscription.id)
      if (payments.data && payments.data.length > 0) {
        firstPayment = payments.data[0]

        // If PIX, get QR code for the first payment
        if (billingType === 'PIX' && firstPayment.id) {
          pix = await getPixQrCode(firstPayment.id)
        }
      }
    } catch (payErr) {
      console.warn('Could not fetch subscription payments:', payErr)
    }

    res.json({
      success: true,
      subscription: {
        id: subscription.id,
        status: subscription.status,
        billingType: subscription.billingType,
        value: subscription.value,
        cycle: subscription.cycle,
        nextDueDate: subscription.nextDueDate,
      },
      payment: firstPayment ? {
        id: firstPayment.id,
        status: firstPayment.status,
        billingType: firstPayment.billingType,
        value: firstPayment.value,
        invoiceUrl: firstPayment.invoiceUrl,
        bankSlipUrl: firstPayment.bankSlipUrl,
      } : null,
      pix,
    })
  } catch (err) {
    console.error('Subscribe error:', err)
    const message = err instanceof Error ? err.message : 'Erro interno'
    res.status(500).json({ error: message })
  }
})

app.listen(PORT, () => {
  const key = process.env.ASAAS_API_KEY || ''
  const masked = key.length > 10 ? key.slice(0, 10) + '...' + key.slice(-4) : '(not set)'
  console.log(`Server running on http://localhost:${PORT}`)
  console.log(`Asaas API: ${process.env.ASAAS_BASE_URL} | Key: ${masked}`)
})
